version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
  - package-ecosystem: bundler
    directory: /gemfiles/rails_61
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
  - package-ecosystem: bundler
    directory: /gemfiles/rails_70
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
