---

require: rubocop-packaging

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 2.7

Metrics:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
