---

require:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 3.1

Capybara:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  Enabled: true

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/RedundantWithinFind:
  Enabled: true

Capybara/RSpec/HaveSelector:
  Enabled: true

Capybara/RSpec/PredicateMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Capybara/VisibilityMatcher:
  Enabled: true

Metrics:
  Enabled: false

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Packaging/BundlerSetupInTests:
  Enabled: true

Packaging/GemspecGit:
  Enabled: true

Packaging/RequireHardcodingLib:
  Enabled: true

Packaging/RequireRelativeHardcodingLib:
  Enabled: true

Performance:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: false

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BindCall:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/Caller:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/Casecmp:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: true
  Exclude:
    - spec/**/*

Performance/CompareWithBlock:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true
  IncludeActiveSupportAliases: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true
  EnabledForFlattenWithoutParams: false

Performance/InefficientHashSearch:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/MapCompact:
  Enabled: false

Performance/MapMethodChain:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantEqualityComparisonBlock:
  Enabled: false

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 2

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: false

Performance/Size:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringBytesize:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Sum:
  Enabled: false

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

RSpec:
  Enabled: true

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AnyInstance:
  Enabled: true

RSpec/AroundBlock:
  Enabled: true

RSpec/Be:
  Enabled: true

RSpec/BeEmpty:
  Enabled: true

RSpec/BeEq:
  Enabled: true

RSpec/BeEql:
  Enabled: true

RSpec/BeNil:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ChangeByZero:
  Enabled: true

RSpec/ClassCheck:
  Enabled: true

RSpec/ContainExactly:
  Enabled: true

RSpec/ContextMethod:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribeMethod:
  Enabled: false

RSpec/DescribeSymbol:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true

RSpec/DescribedClassModuleWrapping:
  Enabled: true

RSpec/Dialect:
  Enabled: true

RSpec/DuplicatedMetadata:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyHook:
  Enabled: true

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/EmptyMetadata:
  Enabled: true

RSpec/Eq:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWithoutDescription:
  Enabled: true

RSpec/ExampleWording:
  Enabled: true

RSpec/ExcessiveDocstringSpacing:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectChange:
  Enabled: true

RSpec/ExpectInHook:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Enabled: true

RSpec/ImplicitBlockExpectation:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true

RSpec/ImplicitSubject:
  Enabled: true

RSpec/IndexedLet:
  Enabled: true

RSpec/InstanceSpy:
  Enabled: true

RSpec/InstanceVariable:
  Enabled: true

RSpec/IsExpectedSpecify:
  Enabled: true

RSpec/ItBehavesLike:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/LeakyConstantDeclaration:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MatchArray:
  Enabled: true

RSpec/MessageChain:
  Enabled: true

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: true

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/MultipleDescribes:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true

RSpec/MultipleSubjects:
  Enabled: true

RSpec/NamedSubject:
  Enabled: true

RSpec/NestedGroups:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: true

RSpec/NotToNot:
  Enabled: true

RSpec/OverwritingSetup:
  Enabled: true

RSpec/Pending:
  Enabled: true

RSpec/PendingWithoutReason:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true

RSpec/ReceiveCounts:
  Enabled: true

RSpec/ReceiveMessages:
  Enabled: true

RSpec/ReceiveNever:
  Enabled: true

RSpec/RedundantAround:
  Enabled: true

RSpec/RedundantPredicateMatcher:
  Enabled: true

RSpec/RemoveConst:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/RepeatedExampleGroupBody:
  Enabled: true

RSpec/RepeatedExampleGroupDescription:
  Enabled: true

RSpec/RepeatedIncludeExample:
  Enabled: true

RSpec/RepeatedSubjectCall:
  Enabled: true

RSpec/ReturnFromStub:
  Enabled: true

RSpec/ScatteredLet:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/SharedContext:
  Enabled: true

RSpec/SharedExamples:
  Enabled: true

RSpec/SingleArgumentMessageChain:
  Enabled: true

RSpec/SkipBlockInsideExample:
  Enabled: true

RSpec/SortMetadata:
  Enabled: true

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: true

RSpec/StringAsInstanceDoubleConstant:
  Enabled: true

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: true

RSpec/SubjectStub:
  Enabled: true

RSpec/UnspecifiedException:
  Enabled: true

RSpec/VariableDefinition:
  Enabled: true

RSpec/VariableName:
  Enabled: true

RSpec/VerifiedDoubleReference:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

RSpec/VoidExpect:
  Enabled: true

RSpec/Yield:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/console

Style/HashSyntax:
  Enabled: true
