---

require:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-performance

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 3.0

Capybara:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  Enabled: true

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/RSpec/HaveSelector:
  Enabled: true

Capybara/RSpec/PredicateMatcher:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Capybara/VisibilityMatcher:
  Enabled: true

Metrics:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Performance:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: false

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BindCall:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/Caller:
  Enabled: true

Performance/CaseWhenSplat:
  Enabled: true

Performance/Casecmp:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: true
  Exclude:
    - spec/**/*

Performance/CompareWithBlock:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true
  IncludeActiveSupportAliases: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true
  EnabledForFlattenWithoutParams: false

Performance/InefficientHashSearch:
  Enabled: true

Performance/IoReadlines:
  Enabled: true

Performance/MapCompact:
  Enabled: false

Performance/MapMethodChain:
  Enabled: false

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: false

Performance/RedundantEqualityComparisonBlock:
  Enabled: false

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true
  MaxKeyValuePairs: 2

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: false

Performance/Size:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Sum:
  Enabled: false

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - bin/console
