---

require: rubocop-packaging

AllCops:
  DisabledByDefault: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  TargetRubyVersion: 3.0

Metrics:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
