# frozen_string_literal: true
source 'http://rubygems.org'

gem 'rake'

group :test do
  gem 'rspec'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
  gem 'pry'
end

group :rails do
  gem 'rails', '~> 7.2.0'
  # Rails 7.2.4 caps connection_pool below 3, whose keyword-argument API breaks cache stores
  gem 'connection_pool', '< 3' # TODO: remove when dropping Rails 7.2 (see rails/rails#56620)
  gem 'rspec-rails'
  gem 'combustion'
  gem 'capybara'
end

gemspec path: "../.."
